### PR TITLE
Rewrite `cargo audit fix`

### LINKED ISSUE #1107: Security vulnerability in `libgit2-sys` potentially affecting us through the `fix` feature
While most of `cargo audit` is ported to `gitoxide` and is unaffected by [RUSTSEC-2024-0013](https://rustsec.org/advisories/RUSTSEC-2024-0013.html) (thanks, @Byron !), the non-default `fix` feature still pulls in vulnerable versions of `libgit2-sys`:

```
Crate:     libgit2-sys
Version:   0.14.2+1.5.1
Title:     Memory corruption, denial of service, and arbitrary code execution in libgit2
Date:      2024-02-06
ID:        RUSTSEC-2024-0013
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0013
Severity:  8.6 (high)
Solution:  Upgrade to >=0.16.2
Dependency tree:
libgit2-sys 0.14.2+1.5.1
└── git2 0.16.1
    ├── crates-index 0.19.13
    │   └── cargo-edit-9 0.9.3
    │       └── rustsec 0.28.5
    │           ├── rustsec-admin 0.8.8
    │           └── cargo-audit 0.19.0
    └── cargo-edit-9 0.9.3
```

We should probably just rewrite it from the ground up in the long term: https://github.com/rustsec/rustsec/issues/938

It's less clear what to do about it in the short term.

### PR DESCRIPTION
**Pull request by Shnatsel**
Does away with editing `Cargo.toml`; instead runs `cargo update` behind the scenes to upgrade vulnerable versions.

Fixes  #1107 and  #1109 by ripping out `cargo-edit` which transitively depends on `libgit2-sys` and a bunch of other outdated versions.

### CODE REVIEW

**Comment by Shnatsel** [comment]
Even as `cargo upgrade` is getting integrated into Cargo, changing the version requirements in Cargo.toml in ways other than "just upgrade everything to latest" has been [explicitly deferred](https://blog.rust-lang.org/inside-rust/2024/02/13/this-development-cycle-in-cargo-1-77.html#merging-cargo-upgrade-into-cargo-update).

Therefore I do believe that this approach is the best way forward.

**Comment by Shnatsel** [comment]
@tarcieri I'd appreciate a review from you, since you were the one who authored the previous `fix` implementation.

File: cargo-audit/src/commands/audit/fix.rs [hunk 1]
```diff
@@ -60,34 +57,112 @@ impl Runnable for FixCommand {
...
+                    let dir = canonical_path.parent().unwrap();
+                    command.current_dir(dir);
+                }
+                // When calling `.status()` the stdout and stderr are inherited from the parent,
+                // so any status or error messages from `cargo update` will automatically be forwarded
+                // to the user of `cargo audit fix`.
+                let status = command.status();
+                match status {
+                    Ok(_) => (),
+                    Err(e) => {
```
Comment (tarcieri) [inline cargo-audit/src/commands/audit/fix.rs:98]:
```suggestion
                if let Err(e) = status {
```

File: rustsec/Cargo.toml [hunk 2]
```diff
@@ -39,7 +36,7 @@ serde_json = "1"
 
 [features]
 default = ["git"]
```
Comment (tarcieri) [inline rustsec/Cargo.toml:38]: With no additional dependencies, `fix` can probably be enabled by default:

```suggestion
default = ["fix", "git"]
```

Comment (Shnatsel) [reply rustsec/Cargo.toml:38]: In that case should I remove the feature outright and just make it always enabled?

**Comment by Shnatsel** [comment]
@tarcieri I removed the `fix` feature from `rustsec`. The module is still documented as experimental, and `cargo audit` still doesn't enable its `fix` subcommand by default.

Is this good to go (both to merge and to release so we can get rid of libgit2 CVEs), or is there something else that should be done first?

**Review by tarcieri — APPROVED** [review]
Looks good now!

Also FWIW, I didn't write the original: it was contributed in a PR.
