### PR TITLE
cargo-lock: improve git source normalization

### LINKED ISSUE #1388: Cargo audit crashes when using optional git dependency
#### Summary

When `Cargo.toml` contains **two or more optional dependencies** from the **same git repository**, `cargo-audit` panics during execution. The issue appears to be related to how the `Cargo.lock` dependency tree is resolved.

#### Reproduction Steps

1. Define multiple optional dependencies pointing to the same Git repository (with different `rev`s or crate names).
2. Enable them as part of a feature set.
3. Run `cargo audit`.

#### Example `Cargo.toml` (failing case):

```toml
[features]
tracy = ["tracing-tracy", "tracy-client"]

[dependencies]
tracing-tracy = { rev = "tracing-tracy-v0.10.1", git = "ssh://git@.../tracy_client.git", optional = true }
tracy-client  = { rev = "tracy-client-v0.15.0",  git = "ssh://git@.../tracy_client.git", optional = true }
```

Running `cargo audit` on a project using the `tracy` feature causes a panic:

```
thread 'main' panicked at 'invalid Cargo.lock dependency tree: Resolution("failed to find dependency: tracy-client 0.15.0 (git+ssh://git@.../tracy_client.git?rev=tracy-client-v0.15.0)")'
```

#### Workarounds

* Commenting out either of the two dependencies allows `cargo audit` to run without errors.
* Removing the `optional = true` flag from both dependencies also prevents the panic.
* Using only one of the dependencies in both the `features` and `[dependencies]` sections avoids the issue.

#### Example `Cargo.toml` (working case):

```toml
[features]
tracy = ["tracy-client"]

[dependencies]
tracy-client = { rev = "tracy-client-v0.15.0", git = "ssh://git@.../tracy_client.git", optional = true }
```

#### Expected Behavior

`cargo audit` should correctly process multiple optional git dependencies—even when they originate from the same repository—and not panic.

#### Environment

* `cargo-audit` version: 0.21.2
* `cargo` version: 1.88.0
* OS: Ubuntu 22:02

#### Additional Notes

The issue does not appear to be a problem with Cargo itself, as the project builds and resolves fine with `cargo build`. The crash is specific to `cargo-audit`'s dependency resolution logic.

### PR DESCRIPTION
**Pull request by djc**
Fixes #1388.

### CODE REVIEW

**Comment by tarcieri** [comment]
Before cutting another major `cargo-lock` release it’d be good to address #1323 too, since it requires breaking changes that involve vendoring some code from upstream cargo

File: cargo-lock/src/package/source.rs [hunk 1]
```diff
@@ -32,19 +32,53 @@ pub struct SourceId {
     /// The source kind.
     kind: SourceKind,
 
-    /// For example, the exact Git revision of the specified branch for a Git Source.
-    precise: Option<String>,
-
```
Comment (tarcieri) [inline cargo-lock/src/package/source.rs:37]: Why was this removed? It still exists upstream: https://github.com/rust-lang/cargo/blob/1ce8023/src/cargo/core/source_id.rs#L56

Comment (djc) [reply cargo-lock/src/package/source.rs:37]: Basically, I was not aware that the code was copied from Cargo at some point, and from reading the code (and running the tests), it seemed to only be used/relevant in the git case. I could probably revert it. Do you have any other feedback I should process?

Comment (tarcieri) [reply cargo-lock/src/package/source.rs:37]: The git case may be relevant to other users of `cargo-lock`.

In general that particular file is vendored from cargo (it's noted at the top, although it seems the URL needs to be updated)

Comment (djc) [reply cargo-lock/src/package/source.rs:37]: It seems to me that the `SourceId` and `SourceKind` stuff in Cargo has gotten a lot more intertwined between 2020 and now, so I'm not sure it's worth doing this. As an alternative, Cargo's cargo-util-schemas crate will include lockfile support in a few releases, so maybe we should drop cargo-lock in favor of using that directly.

Comment (tarcieri) [reply cargo-lock/src/package/source.rs]: Looks like it provides `SourceKind` but not `SourceId`, which doesn't quite seem useful enough to start roping it in, especially since it seems to have breaking changes every few months
